service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - !GetAtt playersTable.Arn

functions:
  createPlayer:
    handler: handler.createPlayer
    environment:
      PLAYER_TABLE: !Ref playersTable
    events:
      - http:
          method: post
          path: players
          cors: true # <-- CORS!

  updatePlayer:
    handler: handler.updatePlayer
    environment:
      PLAYER_TABLE: !Ref playersTable
    events:
      - http:
          method: put
          path: players/{id}
          cors: true # <-- CORS!

  deletePlayer:
    handler: handler.deletePlayer
    environment:
      PLAYER_TABLE: !Ref playersTable
    events:
      - http:
          method: delete
          path: players/{id}
          cors: true # <-- CORS!

  getAllPlayers:
    handler: handler.getAllPlayers
    environment:
      PLAYER_TABLE: !Ref playersTable
    events:
      - http:
          method: get
          path: players
          cors: true

resources:
  Resources:
    playersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: players
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: playerId
            AttributeType: S
        KeySchema:
          - AttributeName: playerId
            KeyType: HASH
