import { Player } from '../App';

export const names: Player[] = [
  {
    value: 'ariKark',
    label: 'Ari Kark',
    tier: 2.5,
    team: null,
  },
  {
    value: 'benjiDorevitch',
    label: 'Benji Dorevitch',
    tier: 1,
    team: null,
  },
  {
    value: 'brandonFriedman',
    label: 'Brandon Friedman',
    tier: 1.2,
    team: null,
  },
  {
    value: 'camLubofsky',
    label: 'Cam Lubofsky',
    tier: 2,
    team: null,
  },
  {
    value: 'danKlotnick',
    label: 'Dan Klotnick',
    tier: 1.1,
    team: null,
  },
  {
    value: 'danShandler',
    label: 'Dan Shandler',
    tier: 1,
    team: null,
  },
  {
    value: 'davidBerlinski',
    label: 'David Berlinski',
    tier: 1.1,
    team: null,
  },
  {
    value: 'davidMarcuson',
    label: 'David Marcuson',
    tier: 1.4,
    team: null,
  },
  {
    value: 'eranKark',
    label: 'Eran Kark',
    tier: 1,
    team: null,
  },
  {
    value: 'gidonFixler',
    label: 'Gidon Fixler',
    tier: 1.9,
    team: null,
  },
  {
    value: 'gregDorfman',
    label: 'Greg Dorfman',
    tier: 3.5,
    team: null,
  },
  {
    value: 'jarrydLudski',
    label: 'Jarryd Ludski',
    tier: 3,
    team: null,
  },
  {
    value: 'jaydBrick',
    label: 'Jayd Brick',
    tier: 1.7,
    team: null,
  },
  {
    value: 'jesseBurns',
    label: 'Jesse Burns',
    tier: 1.7,
    team: null,
  },
  {
    value: 'jordanRubinstein',
    label: 'Jordan Rubinstein',
    tier: 2.8,
    team: null,
  },
  {
    value: 'markTenenbaum',
    label: 'Mark Tenenbaum',
    tier: 2,
    team: null,
  },
  {
    value: 'maxKausman',
    label: 'Max Kausman',
    tier: 2,
    team: null,
  },
  {
    value: 'noahLipshut',
    label: 'Noah Lipshut',
    tier: 2.2,
    team: null,
  },
  {
    value: 'raphaTamir',
    label: 'Rapha Tamir',
    tier: 1.8,
    team: null,
  },
  {
    value: 'robMiller',
    label: 'Rob Miller',
    tier: 1.6,
    team: null,
  },
  {
    value: 'steeleMellet',
    label: 'Steele Mellet',
    tier: 2,
    team: null,
  },
  {
    value: 'talLevin',
    label: 'Tal Levin',
    tier: 2.7,
    team: null,
  },
  {
    value: 'taylorBloom',
    label: 'Taylor Bloom',
    tier: 2.1,
    team: null,
  },
  {
    value: 'zacBlum',
    label: 'Zac Blum',
    tier: 2.8,
    team: null,
  },
];
