import { Player } from '../App';

export const names: Player[] = [
  {
    playerId: 'ariKark',
    name: 'Ari Kark',
    tier: 2.5,
    team: null,
    playing: false,
  },
  {
    playerId: 'benjiDorevitch',
    name: 'Benji Dorevitch',
    tier: 1,
    team: null,
    playing: false,
  },
  {
    playerId: 'brandonFriedman',
    name: 'Brandon Friedman',
    tier: 1.2,
    team: null,
    playing: false,
  },
  {
    playerId: 'camLubofsky',
    name: 'Cam Lubofsky',
    tier: 2,
    team: null,
    playing: false,
  },
  {
    playerId: 'danKlotnick',
    name: 'Dan Klotnick',
    tier: 1.1,
    team: null,
    playing: false,
  },
  {
    playerId: 'danShandler',
    name: 'Dan Shandler',
    tier: 1,
    team: null,
    playing: false,
  },
  {
    playerId: 'davidBerlinski',
    name: 'David Berlinski',
    tier: 1.1,
    team: null,
    playing: false,
  },
  {
    playerId: 'davidMarcuson',
    name: 'David Marcuson',
    tier: 1.4,
    team: null,
    playing: false,
  },
  {
    playerId: 'eranKark',
    name: 'Eran Kark',
    tier: 1,
    team: null,
    playing: false,
  },
  {
    playerId: 'gidonFixler',
    name: 'Gidon Fixler',
    tier: 1.9,
    team: null,
    playing: false,
  },
  {
    playerId: 'gregDorfman',
    name: 'Greg Dorfman',
    tier: 3.5,
    team: null,
    playing: false,
  },
  {
    playerId: 'jarrydLudski',
    name: 'Jarryd Ludski',
    tier: 3,
    team: null,
    playing: false,
  },
  {
    playerId: 'jaydBrick',
    name: 'Jayd Brick',
    tier: 1.7,
    team: null,
    playing: false,
  },
  {
    playerId: 'jesseBurns',
    name: 'Jesse Burns',
    tier: 1.7,
    team: null,
    playing: false,
  },
  {
    playerId: 'jordanRubinstein',
    name: 'Jordan Rubinstein',
    tier: 2.8,
    team: null,
    playing: false,
  },
  {
    playerId: 'markTenenbaum',
    name: 'Mark Tenenbaum',
    tier: 2,
    team: null,
    playing: false,
  },
  {
    playerId: 'maxKausman',
    name: 'Max Kausman',
    tier: 2,
    team: null,
    playing: false,
  },
  {
    playerId: 'noahLipshut',
    name: 'Noah Lipshut',
    tier: 2.2,
    team: null,
    playing: false,
  },
  {
    playerId: 'raphaTamir',
    name: 'Rapha Tamir',
    tier: 1.8,
    team: null,
    playing: false,
  },
  {
    playerId: 'robMiller',
    name: 'Rob Miller',
    tier: 1.6,
    team: null,
    playing: false,
  },
  {
    playerId: 'steeleMellet',
    name: 'Steele Mellet',
    tier: 2,
    team: null,
    playing: false,
  },
  {
    playerId: 'talLevin',
    name: 'Tal Levin',
    tier: 2.7,
    team: null,
    playing: false,
  },
  {
    playerId: 'taylorBloom',
    name: 'Taylor Bloom',
    tier: 2.1,
    team: null,
    playing: false,
  },
  {
    playerId: 'zacBlum',
    name: 'Zac Blum',
    tier: 2.8,
    team: null,
    playing: false,
  },
];
